spring:
  application:
    name: apollo-adminservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003172

server:
  port: 11002

logging:
  file: ~/logs/apollo/apollo-adminservice.log
