spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 11001

logging:
  file: ~/logs/apollo/100003171/apollo-configservice.log
